project:
  type: website

website:
  title: "StatCast Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
        icon: house-door
      - href: stats-context.qmd
        text: Stats Explained
        icon: journal-text
      - href: story.qmd
        text: Correlation
        icon: graph-up
      - href: more-data.qmd
        text: Comparison
        icon: bar-chart-line
      - href: players.qmd
        text: Players
        icon: person-bounding-box
      - href: about.qmd
        text: About
        icon: info-circle
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
