project:
  type: website

website:
  title: "StatCast Data"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: story.qmd
        text: Story
      - href: more-data.qmd
        text: More Data
      - href: players.qmd
        text: Players
      - href: stats-context.qmd
        text: Stats Explained
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
